server:
  port: 8080
    
spring:
  application:
    name: gateway
    
eureka:
  instance: 
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/registry/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 21000
        timeout:
          enabled: true

ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000

#(ribbon.ReadTimeout + ribbon.connectTimeout) * (1+ribbon.maxAutoRetries(default 0) * (ribbon.MaxAutoRetriesNextServer (default 1) + 1)
#timeoutInMilliseconds = (5000 + 5000) * (1+0)*(1+1) = 20000

zuul:
  prefix: #prefix vazio para funcionar o swagger
  ignored-services: "*"

  routes:
    auth:
      service-id: auth
      path: /auth/**
      strip-prefix: false
      custom-sensitive-headers: true

    product:
      service-id: product
      path: /product/**
      strip-prefix: false
      custom-sensitive-headers: true